//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarlosProyecto.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class listaordenes
    {
        public int ordenFactura { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string atributos { get; set; }
        public decimal motor { get; set; }
        public string cliente { get; set; }
        public string ciudad { get; set; }
    }
}
